export function getUiElements() {
  return {
    radius: document.getElementById("radius"),
    damage: document.getElementById("damage"),
    bondWeaken: document.getElementById("bondWeaken"),
    relaxIters: document.getElementById("relaxIters"),
    radiusVal: document.getElementById("radiusVal"),
    damageVal: document.getElementById("damageVal"),
    bondWeakenVal: document.getElementById("bondWeakenVal"),
    relaxItersVal: document.getElementById("relaxItersVal"),
    reset: document.getElementById("reset"),
    structureMode: document.getElementById("structureMode"),
    structureSelect: document.getElementById("structureSelect"),
    structurePreview: document.getElementById("structurePreview"),
    openEditor: document.getElementById("openEditor"),
    editorDialog: document.getElementById("editorDialog"),
    closeEditor: document.getElementById("closeEditor"),
    structureList: document.getElementById("structureList"),
    editorCanvas: document.getElementById("editorCanvas"),
    paintMode: document.getElementById("paintMode"),
    tileType: document.getElementById("tileType"),
    tileColor: document.getElementById("tileColor"),
    editorNew: document.getElementById("editorNew"),
    editorRename: document.getElementById("editorRename"),
    editorDelete: document.getElementById("editorDelete"),
    editorExport: document.getElementById("editorExport"),
    editorImport: document.getElementById("editorImport"),
    structureModal: document.getElementById("structureModal"),
    structureModalTitle: document.getElementById("structureModalTitle"),
    structureModalConfirm: document.getElementById("structureModalConfirm"),
    structureData: document.getElementById("structureData"),
    showQuadTree: document.getElementById("showQuadTree"),
    spawnEntity: document.getElementById("spawnEntity"),
    entityCount: document.getElementById("entityCount"),
  };
}
